## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import tensorflow as tf

In [3]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default
tf.enable_eager_execution()

### Collect Data

In [4]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from scipy.stats import zscore
from scipy import stats
import numpy as np
import os


In [5]:
df = pd.read_csv('Prices.csv')

### Check all columns in the dataset

In [6]:
df.head()
df.tail()
df.shape
df.dtypes
df.describe().transpose()
df.info
df.describe()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

date symbol        open       close         low  \
851259           2016-12-30    ZBH  103.309998  103.199997  102.849998   
851260           2016-12-30   ZION   43.070000   43.040001   42.689999   
851261           2016-12-30    ZTS   53.639999   53.529999   53.270000   
851262  2016-12-30 00:00:00    AIV   44.730000   45.450001   44.410000   
851263  2016-12-30 00:00:00    FTV   54.200001   53.630001   53.389999   

              high     volume  
851259  103.930000   973800.0  
851260   43.310001  1938100.0  
851261   53.740002  1701200.0  
851262   45.590000  1380900.0  
851263   54.480000   705100.0

(851264, 7)

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

count          mean           std   min           25%  \
open    851264.0  7.083699e+01  8.369588e+01  0.85  3.384000e+01   
close   851264.0  7.085711e+01  8.368969e+01  0.86  3.385000e+01   
low     851264.0  7.011841e+01  8.287729e+01  0.83  3.348000e+01   
high    851264.0  7.154348e+01  8.446550e+01  0.88  3.419000e+01   
volume  851264.0  5.415113e+06  1.249468e+07  0.00  1.221500e+06   

                 50%           75%           max  
open    5.277000e+01  7.988000e+01  1.584440e+03  
close   5.280000e+01  7.989000e+01  1.578130e+03  
low     5.223000e+01  7.911000e+01  1.549940e+03  
high    5.331000e+01  8.061000e+01  1.600930e+03  
volume  2.476250e+06  5.222500e+06  8.596434e+08

<bound method DataFrame.info of                        date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
5       2016-01-12 00:00:00   WLTW  115.510002  115.550003  114.500000   
6       2016-01-13 00:00:00   WLTW  116.459999  112.849998  112.589996   
7       2016-01-14 00:00:00   WLTW  113.510002  114.379997  110.050003   
8       2016-01-15 00:00:00   WLTW  113.330002  112.529999  111.919998   
9       2016-01-19 00:00:00   WLTW  113.660004  110.379997  109.870003   
10      2016-01-20 00:00:00   WLTW  109.059998  109.300003  108.320000   
11      2016-01-21 00:00:00   WLTW  109.730003  110.000000  108.320000   
12    

open          close            low           high  \
count  851264.000000  851264.000000  851264.000000  851264.000000   
mean       70.836986      70.857109      70.118414      71.543476   
std        83.695876      83.689686      82.877294      84.465504   
min         0.850000       0.860000       0.830000       0.880000   
25%        33.840000      33.849998      33.480000      34.189999   
50%        52.770000      52.799999      52.230000      53.310001   
75%        79.879997      79.889999      79.110001      80.610001   
max      1584.439941    1578.130005    1549.939941    1600.930054   

             volume  
count  8.512640e+05  
mean   5.415113e+06  
std    1.249468e+07  
min    0.000000e+00  
25%    1.221500e+06  
50%    2.476250e+06  
75%    5.222500e+06  
max    8.596434e+08

### Drop columns `date` and  `symbol`

In [7]:
df= df.drop(labels = "date", axis = 1)
df= df.drop(labels = "symbol", axis = 1)

In [8]:
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [9]:
df=df.iloc[0:1000,:]
df["volume"] = df["volume"]/1000

In [10]:
df.shape
df.dtypes
df.head()

(1000, 5)

open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2163.6
1  125.239998  119.980003  119.940002  125.540001  2386.4
2  116.379997  114.949997  114.930000  119.739998  2489.5
3  115.480003  116.620003  113.500000  117.440002  2006.3
4  117.010002  114.970001  114.089996  117.330002  1408.6

### Divide the data into train and test sets

In [11]:
X = df.iloc[:,0:4]
Y = df['volume']
X.shape
Y.shape


(1000, 4)

(1000,)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=10)

#### Convert Training and Test Data to numpy float32 arrays


In [13]:
train_x = np.float32(X_train)
print(train_x.dtype)
train_y = np.float32(y_train)
print(train_y.dtype)

float32
float32


In [14]:
test_x = np.float32(X_test)
print(test_x.dtype)
test_y = np.float32(y_test)
print(test_y.dtype)

float32
float32


### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x_fit = sc.fit(train_x)
train_x = train_x_fit.transform(train_x)
test_x_fit = sc.fit(test_x)
test_x_std = test_x_fit.transform(test_x)

test_x_std.shape
test_y.shape

(300, 4)

(300,)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [16]:
#Declare Weights and Bias

w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))


2.Define a function to calculate prediction

In [17]:

# y = wx + b

def prediction(x, w, b):
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y


3.Loss (Cost) Function [Mean square error]

In [18]:
#Define Loss

def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg



4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [19]:
#Define Gradient Descent function

def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record math ops on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss w.r.t Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b


## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Test loss at every 5th iteration

In [20]:
#Training the model for 100 iterations

for i in range(100):
    
    w, b = train(train_x, train_y, w, b)
    if i % 5 == 0:
        print('Current Loss on iteration', i, loss(train_y, prediction(train_x, w, b)).numpy())

Current Loss on iteration 0 308311140.0
Current Loss on iteration 5 302536600.0
Current Loss on iteration 10 297818620.0
Current Loss on iteration 15 293963460.0
Current Loss on iteration 20 290813630.0
Current Loss on iteration 25 288240100.0
Current Loss on iteration 30 286137200.0
Current Loss on iteration 35 284418980.0
Current Loss on iteration 40 283015140.0
Current Loss on iteration 45 281867970.0
Current Loss on iteration 50 280930780.0
Current Loss on iteration 55 280165060.0
Current Loss on iteration 60 279539230.0
Current Loss on iteration 65 279028030.0
Current Loss on iteration 70 278610340.0
Current Loss on iteration 75 278268830.0
Current Loss on iteration 80 277990200.0
Current Loss on iteration 85 277762270.0
Current Loss on iteration 90 277576060.0
Current Loss on iteration 95 277423870.0


### Get the shapes and values of W and b

In [21]:

w.shape
w

TensorShape([Dimension(4), Dimension(1)])

<tf.Tensor: id=4483, shape=(4, 1), dtype=float32, numpy=
array([[ 1.9218445e-04],
       [-1.7013549e-04],
       [-4.8542021e-05],
       [ 1.0871886e-06]], dtype=float32)>

In [22]:
b.shape
b

TensorShape([Dimension(1)])

<tf.Tensor: id=4486, shape=(1,), dtype=float32, numpy=array([4972.7715], dtype=float32)>

### Model Prediction on 1st Examples in Test Dataset

In [23]:
w
b

<tf.Tensor: id=4483, shape=(4, 1), dtype=float32, numpy=
array([[ 1.9218445e-04],
       [-1.7013549e-04],
       [-4.8542021e-05],
       [ 1.0871886e-06]], dtype=float32)>

<tf.Tensor: id=4486, shape=(1,), dtype=float32, numpy=array([4972.7715], dtype=float32)>

In [29]:
current_prediction = prediction(test_x, w, b)

current_prediction[0]



<tf.Tensor: id=4520, shape=(1,), dtype=float32, numpy=array([4972.7695], dtype=float32)>

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load tensorflow if not done already

### Load the given Iris data using pandas (Iris.csv)

In [11]:
iris_df = pd.read_csv('Iris.csv')

In [12]:
iris_df.info()
iris_df.shape
iris_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


(150, 6)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

### Splitting the data into feature set and target set

In [13]:
X = iris_df.iloc[:,1:5].values
y = iris_df.iloc[:,5].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

### Divide the dataset into Training and test (70:30)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=1)
print("X_train ", X_train.shape)
print("X_test ", X_test.shape)
print("Y_train ", Y_train.shape)
print("Y_test ", Y_test.shape)

X_train  (105, 4)
X_test  (45, 4)
Y_train  (105, 3)
Y_test  (45, 3)


###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function 

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
# Create model
model = Sequential()

model.add(Dense(10,input_shape=(4,),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(3,activation='softmax'))

#model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_7 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


### Model Training 

In [18]:
### Model Prediction

#fitting the model and predicting 
model.fit(X_train,Y_train,epochs=100)

Epoch 1/100
105/105 [==============================] - 0s 76us/step - loss: 0.7874 - acc: 0.6952
Epoch 2/100
105/105 [==============================] - 0s 76us/step - loss: 0.7821 - acc: 0.6952
Epoch 3/100
105/105 [==============================] - 0s 76us/step - loss: 0.7759 - acc: 0.6952
Epoch 4/100
105/105 [==============================] - 0s 76us/step - loss: 0.7704 - acc: 0.6952
Epoch 5/100
105/105 [==============================] - 0s 76us/step - loss: 0.7648 - acc: 0.6952
Epoch 6/100
105/105 [==============================] - 0s 38us/step - loss: 0.7606 - acc: 0.6952
Epoch 7/100
105/105 [==============================] - 0s 76us/step - loss: 0.7550 - acc: 0.6952
Epoch 8/100
105/105 [==============================] - 0s 114us/step - loss: 0.7511 - acc: 0.6952
Epoch 9/100
105/105 [==============================] - 0s 76us/step - loss: 0.7457 - acc: 0.6952
Epoch 10/100
105/105 [==============================] - 0s 76us/step - loss: 0.7415 - acc: 0.6952
Epoch 11/100
105/105 [======

105/105 [==============================] - 0s 114us/step - loss: 0.5598 - acc: 0.8286
Epoch 85/100
105/105 [==============================] - 0s 76us/step - loss: 0.5611 - acc: 0.8381
Epoch 86/100
105/105 [==============================] - 0s 114us/step - loss: 0.5563 - acc: 0.8286
Epoch 87/100
105/105 [==============================] - 0s 114us/step - loss: 0.5554 - acc: 0.8381
Epoch 88/100
105/105 [==============================] - 0s 76us/step - loss: 0.5529 - acc: 0.8476
Epoch 89/100
105/105 [==============================] - 0s 76us/step - loss: 0.5517 - acc: 0.8571
Epoch 90/100
105/105 [==============================] - 0s 114us/step - loss: 0.5501 - acc: 0.8476
Epoch 91/100
105/105 [==============================] - ETA: 0s - loss: 0.5257 - acc: 0.906 - 0s 76us/step - loss: 0.5485 - acc: 0.8476
Epoch 92/100
105/105 [==============================] - 0s 152us/step - loss: 0.5493 - acc: 0.8381
Epoch 93/100
105/105 [==============================] - 0s 76us/step - loss: 0.5457 - ac

### Model Prediction

In [20]:
from sklearn import metrics
y_pred = model.predict(X_test)

y_test_class = np.argmax(Y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [21]:
#y_predict=model.predict(X_test)
print(metrics.accuracy_score(y_test_class,y_pred_class))
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

0.7777777777777778
              precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       0.90      0.50      0.64        18
           2       0.67      0.92      0.77        13

   micro avg       0.78      0.78      0.78        45
   macro avg       0.80      0.81      0.77        45
weighted avg       0.81      0.78      0.76        45

[[14  0  0]
 [ 3  9  6]
 [ 0  1 12]]


### Save the Model

In [22]:
model.save('mnist_lc.h5')

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?